###############-VERSION-###################
version: '3.3'

################-SERVICIOS-################

services:

###################-REDIS_SHARPS-##########################
   redis1:
    container_name: redis1
    image: redis:6.2.6
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command:
      [
        "redis-server",
        "--bind",
        "redis1",
        "--maxmemory 2mb",
        "--maxmemory-policy allkeys-lfu"
      ]

   redis2:
    container_name: redis2
    image: redis:6.2.6
    restart: always
    ports:
      - "6380:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command:
      [
        "redis-server",
        "--bind",
        "redis2",
        "--maxmemory 2mb",
        "--maxmemory-policy allkeys-lfu"
      ]
  
   redis3:
    container_name: redis3
    image: redis:6.2.6
    restart: always
    ports:
      - "6381:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command:
      [
        "redis-server",
        "--bind",
        "redis3",
        "--maxmemory 2mb",
        "--maxmemory-policy allkeys-random"
      ]
    
