###############-VERSION-###################
version: '3.7'

################-SERVICIOS-################

services:

###################-CLIENTE-GRPC-#########################   
  client:
    container_name: client
    build: ./backend/client
    restart: always
    volumes:
      - ./backend/client:/client
    depends_on:
      - server
    ports:
      - "3000:3000"

###################-SERVIDOR-GRPC-#########################  
  server:
    container_name: server
    build: ./backend/server
    restart: always
    volumes:
      - ./backend/server:/server
    ports:
      - "50051:50051"
  
###################-MEMCACHED-#########################  
  memcached:
    container_name: memcached
    image: bitnami/memcached:latest
    restart: always
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_MAX_CONNECTIONS=2000
      - MEMCACHED_THREADS=4
      - MEMCACHED_USERNAME=memcached
      - MEMCACHED_PASSWORD=memcached
    #command: ["memcached", "-m 64"]